### ISSUE TITLE
Thanks and a question

### ISSUE THREAD

**Issue by germasch** [kokkos/kokkos-spack#5]
Thanks for providing this repo, and the very useful docs that came with it. I found this via google when I ran into troubles using the kokkos package that's included with spack, and so far everything seems to work as advertised ;)

So really the only question I have: Why are you maintaining this in a separate repo, ie., why aren't you just keeping the kokkos package in spack updated?

**Comment by aprokop** [comment]
I second this question. I'd like to update ArborX in Spack, but it needs updated Kokkos.

**Comment by crtrott** [comment]
I think the PR is issued against mainline spack. @jjwilke

**Comment by crtrott** [comment]
https://github.com/spack/spack/pull/16358

**Comment by germasch** [comment]
That's great -- thanks!
